[element]
a = {}
b = {}
button = {}
div = {}
footer = {}
form = {}
h1 = {}
h2 = {}
h3 = {}
h4 = {}
h5 = {}
h6 = {}
header = {}
input = {}
label = {}
li = {}
p = {}
section = {}
span = {}
strong = {}
table = {}
tbody = {}
td = {}
thead = {}
tr = {}
ul = {}
